### ISSUE TITLE
how you install this on odoo ?

### ISSUE THREAD

**Issue by dontspamm** [OCA/connector-accountedge#10]
hey i just discovered this and i wonder how i am supposed to install this on odoo

**Comment by max3903** [comment]
Hello @dontspamm,

This is a set of modules that we used internally at Savoir-faire Linux to integrate Odoo expenses on version 7 with AccountEdge. We don't use them anymore as we now use Odoo for our accounting.

To install them, you need to download those modules, make sure they are in your addons path and install them. I am not sure it requires any additional library.

If you have any issue during the installation, please be more specific.

**Comment by dontspamm** [comment]
so to install a module like this you just place it into odoo/odoo-server/openerp/addons  or into odoo/odoo-server/addons

**Comment by max3903** [comment]
Yes you just place it in `odoo/odoo-server/addons`, with the other addons.
